name: co_bricks
description: Mason bricks synchronization CLI tool
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^9.0.0
  args: ^2.7.0
  cli_completion: ^0.5.1
  collection: ^1.18.0
  mason: ^0.1.0-dev.58
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.10.3
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

executables:
  co-bricks: co_bricks
